{{- if .Values.rconAPI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}-rcon-api
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- range $key, $value := .Values.rconAPI.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{- if semverCompare ">=1.20.0-0" .Capabilities.KubeVersion.Version -}}
  {{- if .Values.rconAPI.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.rconAPI.ipFamilyPolicy }}
  {{- end }}
  {{- end }}
  {{- if semverCompare ">=1.20.0-0" .Capabilities.KubeVersion.Version -}}
  {{- if .Values.rconAPI.ipFamilies }}
  ipFamilies: {{ toYaml .Values.rconAPI.ipFamilies | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ .Values.rconAPI.type }}
  ports:
    - name: http
      port: {{ .Values.rconAPI.httpPort }}
      targetPort: 24180
    {{- if eq .Values.rconAPI.type "NodePort" }}
      nodePort: {{ .Values.rconAPI.httpPort }}
    {{- end }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.rconAPI.grpcPort }}
      targetPort: 24181
    {{- if eq .Values.rconAPI.type "NodePort" }}
      nodePort: {{ .Values.rconAPI.grpcPort }}
    {{- end }}
      protocol: TCP
  selector:
    app: {{ template "factorio-server-charts.fullname" . }}
{{- end }}
