{{- if .Values.rcon.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}-rcon
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- range $key, $value := .Values.rcon.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{- if semverCompare ">=1.20.0-0" .Capabilities.KubeVersion.Version -}}
  {{- if .Values.controller.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.controller.service.ipFamilyPolicy }}
  {{- end }}
  {{- end }}
  {{- if semverCompare ">=1.20.0-0" .Capabilities.KubeVersion.Version -}}
  {{- if .Values.controller.service.ipFamilies }}
  ipFamilies: {{ toYaml .Values.controller.service.ipFamilies | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ .Values.rcon.type }}
  ports:
    - name: rcon
      port: {{ .Values.rcon.port }}
      targetPort: {{ .Values.factorioServer.rcon_port }}
    {{- if eq .Values.rcon.type "NodePort" }}
      nodePort: {{ .Values.rcon.port}}
    {{- end }}
      protocol: TCP
  selector:
    app: {{ template "factorio-server-charts.fullname" . }}
{{- end }}
